#ifndef __6502_H__
#define __6502_H__

#include <stdint.h>

const char COMMENT_CHAR1 = '#';
const char COMMENT_CHAR2 = ';';

enum directives {
	ALIGN,
	ORIGIN,
	BYTE,
	WORD,
	SEGMENT,
	INCLUDE
};

struct directive_defs {
	enum directives directive;
	const char *string;
};

const int DIRECTIVE_SIZE = 6;
const struct directive_defs ASM_DIRECTIVES[6] = {
		{ALIGN, "ALIGN"},
		{ORIGIN, "ORIGIN"},
		{BYTE, "BYTE"},
		{WORD, "WORD"},
		{SEGMENT, "SEGMENT"},
		{INCLUDE, "INCLUDE"}
};

enum addressing_modes{
	NONE,
	ACCUMULATOR,
	IMPLIED,
	IMMEDIATE,
	ABSOLUTE,
	ZERO_PAGE,
	RELATIVE,
	ABSOLUTE_X,
	ABSOLUTE_Y,
	ZERO_PAGE_X,
	ZERO_PAGE_Y,
	INDIRECT,
	INDIRECT_X,
	INDIRECT_Y
};



const int OPCODE_MNEMOIC_SIZE = 76;
const char * const OPCODE_MNEMONICS[76] = {
	//arithmatic and logical opcodes
	"ORA",
	"AND",
	"EOR",
	"ADC",
	"SBC",
	"CMP",
	"CPX",
	"CPY",
	"DEC",
	"DEX",
	"DEY",
	"INC",
	"INX",
	"INY",
	"ASL",
	"ROL",
	"LSR",
	"ROR",

	//data opcodes
	"LDA",
	"STA",
	"LDX",
	"STX",
	"LDY",
	"STY",
	"TAX",
	"TXA",
	"TAY",
	"TYA",
	"TSX",
	"TXS",
	"PLA",
	"PHA",
	"PLP",
	"PHP",

	//jump and flag opcodes
	"BPL",
	"BMI",
	"BVC",
	"BCC",
	"BCS",
	"BNE",
	"BEQ",
	"BRK",
	"RTI",
	"JSR",
	"RTS",
	"JMP",
	"BIT",
	"CLC",
	"SEC",
	"CLD",
	"SED",
	"CLI",
	"SEI",
	"CLV",
	"NOP",

	//illegal opcodes
	"SLO",
	"RLA",
	"SRE",
	"RRA",
	"SAX",
	"LAX",
	"DCP",
	"ISC",
	"ANC",
	"ALR",
	"ARR",
	"XAA",
	"LAX",
	"AXS",
	"SBC",
	"AHX",
	"SHY",
	"SHX",
	"TAS",
	"LAS",
	"KIL"
};

struct opcode_defs{
	uint8_t opcode;
	char *mnemonic;
	enum addressing_modes mode;
};

const struct opcode_defs asm_opcodes[] = {
		{0x00, "BRK", NONE},
		{0x01, "ORA", INDIRECT_X},
		{0x02, "KIL", NONE},
		{0x03, "SLO", INDIRECT_X},
		{0x04, "NOP", ZERO_PAGE},
		{0x05, "ORA", ZERO_PAGE},
		{0x06, "ASL", ZERO_PAGE},
		{0x07, "SLO", ZERO_PAGE},
		{0x08, "PHP", IMPLIED},
		{0x09, "ORA", IMMEDIATE},
		{0x0A, "ASL", IMPLIED},
		{0x0B, "ANC", IMMEDIATE},
		{0x0C, "NOP", ABSOLUTE},
		{0x0D, "ORA", ABSOLUTE},
		{0x0E, "ASL", ABSOLUTE},
		{0x0F, "SLO", ABSOLUTE},
			
		{0x10, "BPL", RELATIVE},
		{0x11, "ORA", INDIRECT_Y},
		{0x12, "KIL", NONE},
		{0x13, "SLO", INDIRECT_Y},
		{0x14, "NOP", ZERO_PAGE_X},
		{0x15, "ORA", ZERO_PAGE_X},
		{0x16, "ASL", ZERO_PAGE_X},
		{0x17, "SLO", ZERO_PAGE_X},
		{0x18, "CLC", IMPLIED},
		{0x19, "ORA", ABSOLUTE_Y},
		{0x1A, "NOP", NONE},
		{0x1B, "SLO", ABSOLUTE_Y},
		{0x1C, "NOP", ABSOLUTE_X},
		{0x1D, "ORA", ABSOLUTE_X},
		{0x1E, "ASL", ABSOLUTE_X},
		{0x1F, "SLO", ABSOLUTE_X},
			
		{0x20, "JSR", ABSOLUTE},
		{0x21, "AND", INDIRECT_X},
		{0x22, "KIL", NONE},
		{0x23, "RLA", INDIRECT_X},
		{0x24, "BIT", ZERO_PAGE},
		{0x25, "AND", ZERO_PAGE},
		{0x26, "ROL", ZERO_PAGE},
		{0x27, "RLA", ZERO_PAGE},
		{0x28, "PLP", IMPLIED},
		{0x29, "AND", IMMEDIATE},
		{0x2A, "ROL", IMPLIED},
		{0x2B, "ANC", IMMEDIATE},
		{0x2C, "BIR", ABSOLUTE},
		{0x2D, "AND", ABSOLUTE},
		{0x2E, "ROL", ABSOLUTE},
		{0x2F, "RLA", ABSOLUTE},
			
		{0x30, "BMI", RELATIVE},
		{0x31, "AND", INDIRECT_Y},
		{0x32, "KIL", NONE},
		{0x33, "RLA", INDIRECT_Y},
		{0x34, "NOP", ZERO_PAGE_X},
		{0x35, "AND", ZERO_PAGE_X},
		{0x36, "ROL", ZERO_PAGE_X},
		{0x37, "RLA", ZERO_PAGE_X},
		{0x38, "SEC", IMPLIED},
		{0x39, "AND", ABSOLUTE_Y},
		{0x3A, "NOP", NONE},
		{0x3B, "RLA", ABSOLUTE_Y},
		{0x3C, "NOP", ABSOLUTE_X},
		{0x3D, "AND", ABSOLUTE_X},
		{0x3E, "ROL", ABSOLUTE_X},
		{0x3F, "RLA", ABSOLUTE_X},
			
		{0x40, "RTI", IMPLIED},
		{0x41, "EOR", INDIRECT_X},
		{0x42, "KIL", NONE},
		{0x43, "SRE", INDIRECT_X},
		{0x44, "NOP", ZERO_PAGE},
		{0x45, "EOR", ZERO_PAGE},
		{0x46, "LSR", ZERO_PAGE},
		{0x47, "SRE", ZERO_PAGE},
		{0x48, "PHA", IMPLIED},
		{0x49, "EOR", IMMEDIATE},
		{0x4A, "LSR", IMPLIED},
		{0x4B, "ALR", IMMEDIATE},
		{0x4C, "JMP", ABSOLUTE},
		{0x4D, "EOR", ABSOLUTE},
		{0x4E, "LSR", ABSOLUTE},
		{0x4F, "SRE", ABSOLUTE},
			
		{0x50, "BVC", RELATIVE},
		{0x51, "EOR", INDIRECT_X},
		{0x52, "KIL", NONE},
		{0x53, "SRE", INDIRECT_Y},
		{0x54, "NOP", ZERO_PAGE_X},
		{0x55, "EOR", ZERO_PAGE_X},
		{0x56, "LSR", ZERO_PAGE_X},
		{0x57, "SRE", ZERO_PAGE_X},
		{0x58, "CLI", IMPLIED},
		{0x59, "EOR", ABSOLUTE_Y},
		{0x5A, "NOP", NONE},
		{0x5B, "SRE", ABSOLUTE_Y},
		{0x5C, "NOP", ABSOLUTE_X},
		{0x5D, "EOR", ABSOLUTE_X},
		{0x5E, "LSR", ABSOLUTE_X},
		{0x5F, "SRE", ABSOLUTE_X},
			
		{0x60, "RTS", IMPLIED},
		{0x61, "ADC", INDIRECT_X},
		{0x62, "KIL", NONE},
		{0x63, "RRA", INDIRECT_X},
		{0x64, "NOP", ZERO_PAGE},
		{0x65, "ADC", ZERO_PAGE},
		{0x66, "ROR", ZERO_PAGE},
		{0x67, "RRA", ZERO_PAGE},
		{0x68, "PLA", IMPLIED},
		{0x69, "ADC", IMMEDIATE},
		{0x6A, "ROR", IMPLIED},
		{0x6B, "ARR", IMMEDIATE},
		{0x6C, "JMP", INDIRECT},
		{0x6D, "ADC", ABSOLUTE},
		{0x6E, "ROR", ABSOLUTE},
		{0x6F, "RRA", ABSOLUTE},
			
		{0x70, "BVS", RELATIVE},
		{0x71, "ADC", INDIRECT_Y},
		{0x72, "KIL", NONE},
		{0x73, "RRA", INDIRECT_Y},
		{0x74, "NOP", ZERO_PAGE_X},
		{0x75, "ADC", ZERO_PAGE_X},
		{0x76, "ROR", ZERO_PAGE_X},
		{0x77, "RRA", ZERO_PAGE_X},
		{0x78, "SEI", IMPLIED},
		{0x79, "ADC", ABSOLUTE_Y},
		{0x7A, "NOP", NONE},
		{0x7B, "RRA", ABSOLUTE_Y},
		{0x7C, "NOP", ABSOLUTE_X},
		{0x7D, "ADC", ABSOLUTE_X},
		{0x7E, "ROR", ABSOLUTE_X},
		{0x7F, "RRA", ABSOLUTE_X},
			
		{0x80, "NOP", IMMEDIATE},
		{0x81, "STA", ZERO_PAGE_X},
		{0x82, "NOP", IMMEDIATE},
		{0x83, "SAX", ZERO_PAGE_X},
		{0x84, "STY", ZERO_PAGE},
		{0x85, "STA", ZERO_PAGE},
		{0x86, "STX", ZERO_PAGE},
		{0x87, "SAX", ZERO_PAGE},
		{0x88, "DEY", IMPLIED},
		{0x89, "NOP", IMMEDIATE},
		{0x8A, "TXA", IMPLIED},
		{0x8B, "XAA", IMMEDIATE},
		{0x8C, "STY", ABSOLUTE},
		{0x8D, "STA", ABSOLUTE},
		{0x8E, "STX", ABSOLUTE},
		{0x8F, "SAX", ABSOLUTE},
			
		{0x90, "BCC", RELATIVE},
		{0x91, "STA", INDIRECT_Y},
		{0x92, "KIL", NONE},
		{0x93, "AHX", INDIRECT_Y},
		{0x94, "STY", ZERO_PAGE_X},
		{0x95, "STA", ZERO_PAGE_X},
		{0x96, "STX", ZERO_PAGE_X},
		{0x97, "SAX", ZERO_PAGE_X},
		{0x98, "TYA", IMPLIED},
		{0x99, "STA", ABSOLUTE_Y},
		{0x9A, "TXS", IMPLIED},
		{0x9B, "TAS", ABSOLUTE_Y},
		{0x9C, "SHY", ABSOLUTE_X},
		{0x9D, "STA", ABSOLUTE_X},
		{0x9E, "SHX", ABSOLUTE_Y},
		{0x9F, "AHX", ABSOLUTE_Y},
			
		{0xA0, "LDY", IMMEDIATE},
		{0xA1, "LDA", INDIRECT_X},
		{0xA2, "LDX", IMMEDIATE},
		{0xA3, "LAX", INDIRECT_X},
		{0xA4, "LDY", ZERO_PAGE},
		{0xA5, "LDA", ZERO_PAGE},
		{0xA6, "LDX", ZERO_PAGE},
		{0xA7, "LAX", ZERO_PAGE},
		{0xA8, "TAY", IMPLIED},
		{0xA9, "LDA", IMMEDIATE},
		{0xAA, "TAX", IMPLIED},
		{0xAB, "LAX", IMMEDIATE},
		{0xAC, "LDY", ABSOLUTE},
		{0xAD, "LDA", ABSOLUTE},
		{0xAE, "LDX", ABSOLUTE},
		{0xAF, "LAX", ABSOLUTE},
			
		{0xB0, "BCS", RELATIVE},
		{0xB1, "LDA", INDIRECT_Y},
		{0xB2, "KIL", NONE},
		{0xB3, "LAX", INDIRECT_Y},
		{0xB4, "LDY", ZERO_PAGE_X},
		{0xB5, "LDA", ZERO_PAGE_X},
		{0xB6, "LDX", ZERO_PAGE_Y},
		{0xB7, "LAX", ZERO_PAGE_Y},
		{0xB8, "CLV", IMPLIED},
		{0xB9, "LDA", ABSOLUTE_Y},
		{0xBA, "TXS", IMPLIED},
		{0xBB, "LAS", ABSOLUTE_Y},
		{0xBC, "LDY", ABSOLUTE_X},
		{0xBD, "LDA", ABSOLUTE_X},
		{0xBE, "LDX", ABSOLUTE_Y},
		{0xBF, "LAX", ABSOLUTE_Y},
			
		{0xC0, "CPY", IMMEDIATE},
		{0xC1, "CMP", INDIRECT_X},
		{0xC2, "NOP", IMMEDIATE},
		{0xC3, "DCP", INDIRECT_X},
		{0xC4, "CPY", ZERO_PAGE},
		{0xC5, "CMP", ZERO_PAGE},
		{0xC6, "DEC", ZERO_PAGE},
		{0xC7, "DCP", ZERO_PAGE},
		{0xC8, "INY", IMPLIED},
		{0xC9, "CMP", IMMEDIATE},
		{0xCA, "DEX", IMPLIED},
		{0xCB, "AXS", IMMEDIATE},
		{0xCC, "CPY", ABSOLUTE},
		{0xCD, "CMP", ABSOLUTE},
		{0xCE, "DEC", ABSOLUTE},
		{0xCF, "DCP", ABSOLUTE},
			
		{0xD0, "BNE", RELATIVE},
		{0xD1, "CMP", INDIRECT_Y},
		{0xD2, "KIL", NONE},
		{0xD3, "DCP", INDIRECT_Y},
		{0xD4, "NOP", ZERO_PAGE_X},
		{0xD5, "CMP", ZERO_PAGE_X},
		{0xD6, "DEC", ZERO_PAGE_X},
		{0xD7, "DCP", ZERO_PAGE_X},
		{0xD8, "CLD", IMPLIED},
		{0xD9, "CMP", ABSOLUTE_Y},
		{0xDA, "NOP", NONE},
		{0xDB, "DCP", ABSOLUTE_Y},
		{0xDC, "NOP", ABSOLUTE_X},
		{0xDD, "CMP", ABSOLUTE_X},
		{0xDE, "DEC", ABSOLUTE_X},
		{0xDF, "DCP", ABSOLUTE_X},
			
		{0xE0, "CPX", IMMEDIATE},
		{0xE1, "SBC", INDIRECT_X},
		{0xE2, "NOP", IMMEDIATE},
		{0xE3, "ISC", INDIRECT_X},
		{0xE4, "CPX", ZERO_PAGE},
		{0xE5, "SBC", ZERO_PAGE},
		{0xE6, "INC", ZERO_PAGE},
		{0xE7, "ISC", ZERO_PAGE},
		{0xE8, "INX", IMPLIED},
		{0xE9, "SBC", IMMEDIATE},
		{0xEA, "NOP", NONE},
		{0xEB, "SBC", IMMEDIATE},
		{0xEC, "CPX", ABSOLUTE},
		{0xED, "SBC", ABSOLUTE},
		{0xEE, "INC", ABSOLUTE},
		{0xEF, "ISC", ABSOLUTE},
			
		{0xF0, "BEQ", RELATIVE},
		{0xF1, "SBC", INDIRECT_Y},
		{0xF2, "KIL", NONE},
		{0xF3, "ISC", INDIRECT_Y},
		{0xF4, "NOP", ZERO_PAGE_X},
		{0xF5, "SBC", ZERO_PAGE_X},
		{0xF6, "INC", ZERO_PAGE_X},
		{0xF7, "ISC", ZERO_PAGE_X},
		{0xF8, "SED", IMPLIED},
		{0xF9, "SBC", ABSOLUTE_Y},
		{0xFA, "NOP", NONE},
		{0xFB, "ISC", ABSOLUTE_Y},
		{0xFC, "NOP", ABSOLUTE_X},
		{0xFD, "SBC", ABSOLUTE_X},
		{0xFE, "INC", ABSOLUTE_X},
		{0xFF, "ISC", ABSOLUTE_X}
};

#endif
